server:
  port: 80
  servlet:
    context-path: /

spring:
  http:
    encoding:
      force: true   #使用阿里的fastJson时必须配置此项，不然会乱码

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.aidilude.betdice.mapper: debug  # 添加sql日志输出
  config: classpath:config/logback.xml